# -*- mode: ruby -*-
# vi: set ft=ruby :
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "WAS"
  config.vm.network "public_network"
  config.vm.synced_folder "DB_PHP/", "/var/www/html"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "was-1tier"
    vb.memory = 1024
    vb.cpus = 1
  config.vm.provision "shell", path: "web-provision.sh"
  config.vm.provision "shell", path: "db-provision.sh"
  end
end