Vagrant.configure("2") do |config|

  # All Server set
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = true

  # Create ubuntu server
  config.vm.define "ubuntuVm" do |ubuntuVm|
    ubuntuVm.vm.hostname = "ubuntuVM"
    ubuntuVm.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--groups", "/was-Lab"]
      v.name = "was-server"
      v.memory = 4096
      v.cpus = 2
      v.linked_clone = true
    end
    ubuntuVm.vm.synced_folder "DB_PHP", "/var/www/html"
    ubuntuVm.vm.network "private_network", ip: "192.168.10.40"
    ubuntuVm.vm.network "forwarded_port", guest: 80, host: 8080

    ubuntuVm.vm.provision "shell", inline: <<-SHELL
    sudo su -
    useradd -m -s /bin/bash wuser
    echo "wuser:wuser" | chpasswd
    echo "root:admin" | chpasswd
    apt-get update
    apt-get install -y apache2 mysql-server php libapache2-mod-php php-mysql
    systemctl enable apache2
    a2enmod rewrite
    systemctl restart apache2
    SHELL
  end
end