# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# START HERE

Vagrant.configure("2") do |config|

  # WAS
  config.vm.define "WAS" do |was|
    was.vm.box = "ubuntu/focal64"
    was.vm.hostname = "was"
    # Private network
    was.vm.network "private_network", ip: "192.168.56.50", subnet: "255.255.255.0"
    was.vm.synced_folder "./DB_PHP", "/var/www/html"

    # Virtualbox
    was.vm.provider "virtualbox" do |vb|
      vb.name = "was-2tier"
      vb.memory = 1024
      vb.cpus = 1
    end
    # Scripts
    was.vm.provision "shell", path: "web-provision.sh"
  end

  # DB
  config.vm.define "DB" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "db"
    # Private network
    db.vm.network "private_network", ip: "192.168.56.51", subnet: "255.255.255.0"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db-2tier"
      vb.memory = 1024
      vb.cpus = 1
    end
    db.vm.provision "shell", path: "db-provision.sh"
  end
end
