Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "TEST"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "TEST-1tier"
    vb.memory = 1024
    vb.cpus = 1
  end
end