apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CLUSTER_NAME
  region: $AWS_DEFAULT_REGION


privateCluster:
  enabled: true
  additionalEndpointServices:
    - "autoscaling"


vpc:
  subnets:
    private:
      ap-northeast-2a: { id: subnet-0f9d81587f2328168 }
      ap-northeast-2c: { id: subnet-0822da32905929d13 }

nodeGroups:
  - name: $CLUSTER_NAME-work-ng
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      allow: true  # Enable SSH access
      sourceSecurityGroupIds:
        - sg-0c7f92b4ad3da9d02  # Replace with the security group ID that controls worker node access

managedNodeGroups:
  - name: $CLUSTER_NAME-managed-ng
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    ssh:
      allow: true  # Enable SSH access
      sourceSecurityGroupIds:
        - sg-0c7f92b4ad3da9d02  # Replace with the security group ID that controls worker node access